### PR TITLE
Add build script

### PR DESCRIPTION
**Pull request by VSEphpbb**

### CODE REVIEW

**Comment by michaelcullum** [comment]
Would someone other than me (with experience with phing) mind taking this one?

**Comment by VSEphpbb** [comment]
@michaelcullum The build script was written by @nickvergessen 

The usage would simply be to `cd` to this extensions root dir, then call phing, presumably from a checked out copy of phpBB. 

This is just to simplify the building of our packages

**Comment by michaelcullum** [comment]
Oh I know that. I just don't want to be the sole reviewer of something I don't understand entirely.

**Comment by nickvergessen** [comment]
Looks good to me (but i reviewed it on my phone, so i didnt check whether the dont edit below section was edited ;) )

**Pull request merged**
