### PR TITLE
Fix issues with identical min/max values

### LINKED ISSUE #76: Problems with 0 min and 0 max values
Submitting Auto Groups settings with 0 min and 0 max at the same time yields the following issues:

Posts type:
All board members are added to the group. Technically this is correct, if all users have at least 1 post, and there is no maximum limit. But it also seems illogical.

User Age type:
All board members are added to the group. This is also correct, since all users are older than 0 but is sort of the same issue as with posts.

Warnings type:
> SQL ERROR [ mysqli ]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') OR ug.group_id = '12') AND u.user_type NOT IN (1, 2) GROUP BY u.user_id' at line 1 [1064]
SQL
SELECT DISTINCT u.user_id, u.user_warnings FROM (phpbb_users u) LEFT JOIN phpbb_user_group ug ON (u.user_id = ug.user_id) WHERE (() OR ug.group_id = '12') AND u.user_type NOT IN (1, 2) GROUP BY u.user_id

The main bug to fix is with Warnings. But I think it may also be worth not allowing 0 values for both max and min to be allowed at the same time, since that could inadvertently auto group all a board's users.

### PR DESCRIPTION
**Pull request by VSEphpbb**
Fixes #76

### CODE REVIEW

**Comment by rxu** [comment]
The patch looks ok, but probably we need to add ```min == max``` including ```0 == 0``` cases to the tests.

**Comment by VSEphpbb** [comment]
Should only need to test the trigger error occurs.

**Comment by VSEphpbb** [comment]
Updated

**Comment by rxu** [comment]
Looks good for me.

**Comment by VSEphpbb** [comment]
@michaelcullum

**Pull request merged**
