### PR TITLE
ACP Component

### PR DESCRIPTION
**Pull request by VSEphpbb**

### CODE REVIEW

**Comment by michaelcullum** [comment]
@rxu @ForumHulp @Pico Please could you **all** review this (and post back if you think it looks okay or make any necessary comments)?

I shouldn't be the only one reviewing @VSEphpbb's stuff, you guys are more than capable of finding errors/commenting on how things are done etc. as well. Don't be afraid to question stuff.

**Comment by rxu** [comment]
When you install this branch to the board and try to create a group rule, you get ```There are no user groups.``` at the <strong>Group</strong> option. When you try to submit the form, you get ```The submitted form was invalid. Try submitting again.``` error as ```'autogroups_group_id'``` value is 0.
I guess this is because there're no autogroups at the very start, but you have no option to create even 1 currently.
Unless I'm missing something obvious here.

**Comment by VSEphpbb** [comment]
@rxu You need to create some Groups. Auto Grouping only works for custom user groups as it would not make sense to be auto-grouping people in and out of the default groups that come with phpBB, as those include registered users, admins, mods, etc.

**Comment by rxu** [comment]
@VSEphpbb This should be stated, f.e., at the ACP module description, as it could be unobvious. Also, if there're no custom groups exist, it looks senseless to be able to submit the form with no user group selected as all you'll get is the error.

**Comment by VSEphpbb** [comment]
Fair point. I think it's better to show the user the error of their ways in usage. So instead if there are no valid predefined groups to use, the menu will show No groups available, and if the user submits, they get a full explanation of what they need to do.

**Comment by rxu** [comment]
It's much better now, thanks. Although, for my taste, I'd add the explaination to the ext ACP front page rather than making user go the whole way to the error message :P
Anyway, I think functional issues like this can be resolved later on. The PR looks good for me.

**Pull request merged**
