### PR TITLE
Fix spelling typos in variable name

### PR DESCRIPTION
**Pull request by VSEphpbb**

### CODE REVIEW

**Comment by rxu** [comment]
The PR looks good, despite the useless(?) spaces before the asterisks in doclblocks (unrelated though),

**Comment by VSEphpbb** [comment]
@rxu Those spaces are the new way of doing things. It's what the IDE's used by most of us do by default (actually can't even be changed) and also the format shown by the PHP documentors (http://www.phpdoc.org/docs/latest/guides/docblocks.html#summary). TO the future!

**Comment by rxu** [comment]
Ah, ok then. It's just not consistent through our code (including phpBB core).

**Comment by VSEphpbb** [comment]
We're starting to use it the new way now, with new stuff. It's officially allowed either way (space or no space). Nobody has bothered to update it all, though, in the core.

**Pull request merged**
